version: '3.4'

services:
  mssqldatabase.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DbConnection= Server=docker-ms-sql-server,1433;Database=MsSqlLib;User Id =SA;Password=MyPass@word; TrustServerCertificate=True;
    ports:
      - "8080"

  mssql:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPass@word
      - User Id=SA;
    ports:
      - "33063:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql/data

volumes:
  mssql-data:

