name: CI pipeline .NET

on:
  push:
    branches: ["master"]
  pull_request:
      branches: [ "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ./packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}    
      - name: Restore dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build --no-restore 
      - name: Test
        run: dotnet test --verbosity normal